### PR TITLE
The Hardest Button to Button: Button Audit

### LINKED ISSUE #230: Button states audit of Keep website
Ran through an audit of the button styles on the [Keep website](https://keep.network/) (version July 22, 2020)

Below is a list of inconsistent button styles. I've listed them as a task checklist so we can fix them in an ad hoc manner as there is time for it. There are screenshots for each one and a screenshot with the style corrected in the comments on this issue. 

@Shadowfiend @ironng @mhluongo — you all have worked on updating some sections of the website recently, so I'll go ahead and tag you here.

Refer to [design system Figma file](https://www.figma.com/file/ARAMFLMOPal0JewjvlZGhX/Keep-Design-System?node-id=787%3A1141) and [Keep website Figma file](https://www.figma.com/file/lw986GpKJjWATIGVHcyMTg/Keep-Website?node-id=337%3A0). 

### Button styling issues
**Home**
- [ ] `Go to TBTC website` hover state and click state
- [ ] `Read Blog Post` hover state and click state
- [ ] `See all` hover state and click state
- [ ] `See less` hover state and click state
- [ ] Validation state and click state for Discord email input button
- [ ] Validation state and click state for newsletter email input button

**Press**
- [ ] `View` hover and click state
- [ ] Click state of `Download` media kit

**Footer**
- [ ] Hover and click state for `Email Us`

### LINKED ISSUE #248: Footer links for Team and Advisors are broken on mobile
On mobile device, the footer links to Team and Advisors don't work.

Issue appears to occur just from the footer from the Press page.

### PR DESCRIPTION
**Pull request by ironng**
> 🎵 🥁 🎸 [Hit it](https://www.youtube.com/watch?v=K4dx42YzQCE)

Buttons up our buttons - updates button styles to match current designs. Also cleans up our color variables, addresses some notes from the previous PR, and fixes broken footer links.

[Preview](https://preview.keep.network/buttons)

Closes #230 
Closes #248

### CODE REVIEW

**Comment by Shadowfiend** [comment]
A few things:
- View the GitHub Repository is still transitioning to blue background on press 😞 It also isn't transitioning to a white arrow on hover :/
- The lack of `href` on the “Get Email Updates” link (I think) means it's not getting a tab index if you're tabbing around the page.
- The “Read Blog Post” link in the tBTC section isn't getting any sort of focus indication (the black links seem to get `:active` styles on `:focus`).
- The submit button for the “Join mailing list” form still has 3d-button-ey borders and its active state is white-background (this may be intentional, not sure, it's just different so wanted to call it out).
- The footer links that are in-page (Team, Advisors) don't get hover underlines.

I'm *guessing* adding an `href` with the appropriate page id anchor to Get Email Updates + Team/Advisors will be enough to give them proper hover/tab behavior.

**Comment by liz-shinn** [comment]
Yay!!! Buttons are looking buttontastic. Another thing I saw in addition to what Antonio mentions above:

- The `Read Blog Post` under tBTC section (Featured Application) is throwing a 500 error.

**Comment by liz-shinn** [comment]
Ah, another thing; looks like we are doing double validation on the email input. Didn't catch that before:
validation

Instead of the `Oops, that doesn't look like an email` text, can we replace that with popover text? As in, print the text that's showing up in the popovers beneath the input.
These were 2 notifications I saw, but there might be other ones:
"Please enter a part following liz@..."
"Please include an @ in the email address..."

**Comment by Shadowfiend** [comment]
Messing with the validation is pretty out of scope. Also, I'm pretty sure what you're seeing is extra browser validation.

**Comment by Shadowfiend** [comment]
... I'm also not seeing that 500 error 🤔

**Comment by liz-shinn** [comment]
Hmm, yup I can't replicate the 500 error again. Who knows! I'm viewing on Chrome. 

That's odd about the browser applying it's own validation; I tested on tbtc.network out of curiosity to see if it did the same thing on that email input and it didn't.

Screen Shot 2020-08-11 at 3 28 05 PM

**Comment by ironng** [comment]
@Shadowfiend @liz-shinn Thanks for your notes! This is ready for re-review :)

@Shadowfiend is correct about the popover validation messages being extra default browser validation. You don't see it on the tbtc site because the input field used there is designated as `type=text` instead of `type=email`. `type=email` is the better choice. Not sure if we can update/control those popovers - will have to look into it.

**Comment by liz-shinn** [comment]
Fwiw I think that the popovers are providing more actionable info about what's wrong with the input entry. It was jarring to see two different validations applied to the same input, but the popover info is useful.

File: src/components/Footer.js [hunk 1]
```diff
@@ -20,9 +20,9 @@ export const FooterTemplate = ({
         <ul className="footer-column-1">
           <li className="keep-logo">Keep</li>
           <li>
-            <Button className="email-btn" href={`mailto:${emailLink.email}`}>
+            <button className="email-btn" href={`mailto:${emailLink.email}`}>
```
Comment (Shadowfiend) [inline src/components/Footer.js:23]: If we're `href`ing we should really use an `a` :/

Comment (Shadowfiend) [reply src/components/Footer.js:23]: Ah, yeah---it actually looks like this doesn't work with a `button`, at least in Safari.

File: src/components/Link.js [hunk 2]
```diff
@@ -1,9 +1,20 @@
...
+import { useLocation } from "@reach/router"
 import PropTypes from "prop-types"
 
 const Link = ({ url, children, ...props }) => {
+  /* eslint-disable no-var */
+  try {
+    var location = useLocation()
+  } catch (error) {
+    var location = window.location
+  }
```
Comment (Shadowfiend) [inline src/components/Link.js:13]: As ugly as the pattern I showed was, I think `let` is actually still better than using `var` here. The scoping characteristics of `var` are a little weird, and `let` is very explicit about what we're doing.

In a perfect world I'd want this to be a `const`, but that won't work with the gymnastics we have to pull.

File: src/components/Footer.js (hunk 1 above)
Comment (Shadowfiend) [reply src/components/Footer.js:23]: Looks like this button also shrank in size---may have been on purpose, just flagging it.

File: src/components/Link.js (hunk 2 above)
Comment (ironng) [reply src/components/Link.js:13]: I agree about using the `let` pattern actually! I just went with this because using the `let` pattern in the tbtc-website repo caused a compilation error that broke the build. However, I tried it with `let` here and what do you know, it's completely fine here.  Maybe because in the tbtc-repo it was in a component wrapped in a `StaticQuery`? Or the gatsby version is different? Not going to investigate right now, but I updated this!

File: src/components/Footer.js (hunk 1 above)
Comment (ironng) [reply src/components/Footer.js]: Whoops! Sorry I was stuck in button land! 😆  Updated.

File: src/components/Link.js (hunk 2 above)
Comment (Shadowfiend) [reply src/components/Link.js:13]: Weird. Another fun surprise for another day lolol.
